apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: todolist-app
  name: mysqld-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi