apiVersion: v1
kind: Service
metadata:
  namespace: todolist-app
  name: mysqld
  labels:
    app: mysqld
spec:
  selector:
    app: mysqld
  type: NodePort
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30000


# apiVersion: v1
# kind: Service
# metadata:
#   namespace: todolist-app
#   name: mysqld
# spec:
#   ports:
#   - port: 3306
#   selector:
#     app: mysql
#   clusterIP: None