apiVersion: v1
kind: Service
metadata:
  namespace: todolist-app
  name: web
  labels:
    app: web
spec:
  selector:
    app: web
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30001