apiVersion: v1
kind: Service
metadata:
  namespace: todolist-app
  name: mysqld
  labels:
    app: mysqld
spec:
  selector:
    app: mysqld
  type: NodePort
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
      nodePort: 30000